version: "3.5"

services:
  bot:
    container_name: telegram-bot
    build: .
    restart: always
    volumes:
      - .:/app

  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_VERSION:-latest}
    volumes:
        - ./ollama:/root/.ollama
        - ./Modelfiles/:/Modelfiles/
    ports:
        - ${OLLAMA_PORT:-11434}:11434
