version: "3.5"

services:
  kyoko:
    container_name: python-kyoko
    build: .
    restart: always
    volumes:
      - .:/app

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
        - ollama:/root/.ollama
    ports:
        - 11434:11434
