version: "3.5"

services:
  signal-api:
    image: bbernhard/signal-cli-rest-api
    restart: always
    ports:
      - ${SIGNAL_API_PORT:-8080}:8080
    volumes:
      - .local/share/signal-cli:/home/.local/share/signal-cli
    environment:
      MODE: normal
