version: "3.5"

services:
  kyoko:
    container_name: python-kyoko
    build: .
    restart: always
    volumes:
      - .:/app

  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_VERSION:-latest}
    volumes:
        - ./ollama:/root/.ollama
        - ./Modelfile:/Modefile
    ports:
        - ${OLLAMA_PORT:-11434}:11434
